# Generated by Django 2.2.6 on 2019-10-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filtermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Add', models.CharField(max_length=30)),
                ('Dept', models.CharField(max_length=30)),
                ('Sub', models.CharField(max_length=30)),
                ('Date', models.DateField()),
            ],
        ),
    ]
